version: '3.2'
services:
  myapp:
    build:
      context: myapp
      args:
        goPackage: github.com/prometheus-community/prometheus-playground/go-app/myapp
        goVersion: 1.11
      cache_from:
      - golang:1.11
      - scratch
    ports:
    - 2112:2112
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
